project_name: sn-sync

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go mod tidy

# join mac binaries into one
universal_binaries:
  - id: sn-sync-macos
    ids:
      - sn-sync-macos-amd64
      - sn-sync-macos-arm
    name_template: "sn"
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post: |
        sh -c 'cat <<EOF > /tmp/sn-sync-gon-universal.hcl
            source = ["./dist/sn-sync-macos_darwin_all/sn-sync"]
            bundle_id = "uk.co.lessknown.sn-cli"
            apple_id {
              username = "jon@lessknown.co.uk"
              password = "@env:AC_PASSWORD"
            }
            sign {
              application_identity = "Developer ID Application: Jonathan Hadfield (VBZY8FBYR5)"
            }
            zip {
              output_path = "./dist/sn-sync_Darwin_all.zip"
            }
        EOF
        gon /tmp/sn-sync-gon-universal.hcl
        '

builds:
  - id: sn-sync-macos-amd64
    main: ./cmd/sn-sync/
    binary: sn-sync
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"

  - id: sn-sync-macos-arm
    main: ./cmd/sn-sync/
    binary: sn-sync
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"

  - id: sn-sync
    main: ./cmd/sn-sync/
    binary: sn-sync
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      linux: Linux
      386: i386
      amd64: x86_64
    builds:
      - sn-sync
    format: tar.gz
    files:
      - none*

release:
  github:
    owner: jonhadfield
    name: sn-sync
  prerelease: auto
  name_template: '{{ .Tag }}'
  extra_files:
    - glob: ./dist/sn-sync_Darwin*.zip

announce:
  skip: true

snapshot:
  name_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
    - README
    - test
    - ignore

checksum:
  extra_files:
    - glob: ./dist/sn-sync_Darwin*.zip
  name_template: 'checksums.txt'