language: go

go:
  - 1.16.x

os:
  - linux

sudo: false
install:
  - go get golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls
  - go get -t -v ./...
env:
  - GO111MODULE=on
script:
  - go test -v -p 1 -parallel 1 -failfast -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - goveralls -coverprofile=coverage.txt -service=travis-ci